version: '3.8'
services:
  db:
    image: postgres:14.6-alpine
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      #докер берет переменные окружения из .env
    volumes:
      - diploma_pg_data_1:/var/lib/postgresql/data/ #здесь записываем в том данные
    ports:
      - "5432:5432"
    healthcheck: #проверка того, что у нас приложение здорово, принимает пользователя и базу
      test: pg_isready -U postgres -d postgres
      timeout: 3s #даем время прогрузиться
      retries: 10
      interval: 3s
#делаем сборку

  frontend:
    image: sermalenk/skypro-front:lesson-36
    ports:
      - "80:80"
    extra_hosts:
      - "api:host-gateway"
    volumes:
       - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf #пробрасыаем тот путь, откуда мы его забрали
       - ./static:/usr/share/nginx/html/static #сюда мы положим статику

volumes:
  diploma_pg_data_1: #здесь мы создаем том
