# Generated by Django 4.0.1 on 2023-05-21 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0008_alter_goalcategory_board'),
    ]

    operations = [
    ]
